version: '3.8'

services:
    web:
        image: php:8.0-alpine
        # This docker instance is run as local unprivileged user instead of root (avoiding file permission issues)
        # `$HOST_USER` is defined in Makefile
        env_file:
            - .env
        user: ${HOST_USER}
        container_name: p2p-care-reminder-bot
        networks:
            - caring-circles
        environment:
            docker: "true"
        init: true
        command: php -S 127.0.0.1:8080 -t public
        volumes:
            - ./:/var/app/
            - composer:/tmp/composer
            - logs:/var/app/logs
        working_dir: /var/app/

networks:
    caring-circles:
        name: caring-circles

volumes:
    composer:
        driver: local
    logs:
        driver: local
